# .github/workflows/ci-cd.yaml
name: Django CI/CD Pipeline # Красивое название для нашего пайплайна

on:
  push: # Запускаем этот пайплайн при каждом "push"
    branches:
      - main # Только когда изменения попадают в ветку 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Будем запускать это на последней версии Ubuntu

    steps:
      - name: Checkout repository # Шаг 1: Загружаем наш код из репозитория
        uses: actions/checkout@v2

      - name: Set up Python 3.13 # Шаг 2: Настраиваем Python, как ты и хотел!
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' # Указываем конкретную версию Python

      - name: Install dependencies # Шаг 3: Устанавливаем все библиотеки из requirements.txt
        run: |
          python -m pip install --upgrade pip # Обновляем pip на всякий случай
          pip install -r requirements.txt # Устанавливаем все зависимости

      - name: Run Django tests # Шаг 4: Запускаем наши Django-тесты
        run: |
          # Перед запуском тестов Django нужно убедиться, что база данных готова
          # Для этого мы можем применить миграции.
          # В реальных проектах на CI/CD часто используют временную базу данных (например, SQLite для тестов).
          python manage.py migrate --noinput
          python manage.py test # Запускаем все тесты в проекте Django
